FROM debian:stretch AS build

ARG matryoshka_version=271c9d5

WORKDIR /build

RUN apt-get -y update && \
  apt-get install -y curl git && \
  curl -L -o /tmp/go.tar.gz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz && \
  tar xzf /tmp/go.tar.gz && \
  mv go /usr/local/ && \
  rm /tmp/go.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

RUN git clone https://github.com/nicktrav/matryoshka.git . && \
  git checkout ${matryoshka_version} && \
  go build -o matryoshka ./cmd/main.go

FROM debian:stretch

COPY --from=build /build/matryoshka /usr/local/bin/

RUN apt-get update
