version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: docker build -t dotfiles -f Dockerfile-debian .
      - run:
          command: docker run --rm -it -v $(pwd):/deps dotfiles matryoshka -dir /deps -debug
